name: frontend
description: "PoemVision AI - Transform your images into beautiful poems"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  animated_introduction: ^1.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  
  # Navigation
  go_router: ^12.1.1
  
  # State Management & DI
  get_it: ^7.6.4
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  
  # Network
  dio: ^5.3.3
  connectivity_plus: ^5.0.1
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Utils
  logger: ^2.0.2
  intl: ^0.18.1
  uuid: ^4.1.0
  path_provider: ^2.1.1
  path: ^1.8.3
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  
  # Image & Media
  image_picker: ^1.0.4
  photo_view: ^0.14.0
  image_gallery_saver: ^2.0.3
  
  # Analytics
  firebase_core: ^2.19.0
  firebase_analytics: ^10.6.3
  
  # Device
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  mocktail: ^1.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700

# App Icon Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#6A4C93"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"

# Splash Screen Configuration
flutter_native_splash:
  color: "#6A4C93"
  image: assets/images/splash_logo.png
  color_dark: "#4A2C73"
  image_dark: assets/images/splash_logo.png

  android_12:
    image: assets/images/splash_logo.png
    icon_background_color: "#6A4C93"
    image_dark: assets/images/splash_logo.png
    icon_background_color_dark: "#4A2C73"
